// Research/Card Scanner Types

export interface Player {
    name: string;
    sport: string;
    prizmRookieYear?: number;
}

export const defaultPlayers: Player[] = [
    { name: 'LeBron James', sport: 'Basketball' },
    { name: 'Michael Jordan', sport: 'Basketball' },
    { name: 'Stephen Curry', sport: 'Basketball' },
    { name: 'Nikola Jokić', sport: 'Basketball' },
    { name: 'Giannis Antetokounmpo', sport: 'Basketball' },
    { name: 'Shai Gilgeous-Alexander', sport: 'Basketball' },
    { name: 'Luka Dončić', sport: 'Basketball' },
    { name: 'Anthony Edwards', sport: 'Basketball' },
    { name: 'Victor Wembanyama', sport: 'Basketball' },
    { name: 'Jayson Tatum', sport: 'Basketball' },
    { name: 'Kevin Durant', sport: 'Basketball' },
    { name: 'Cade Cunningham', sport: 'Basketball' },
    { name: 'Jalen Brunson', sport: 'Basketball' },
    { name: 'Devin Booker', sport: 'Basketball' },
    { name: 'Damian Lillard', sport: 'Basketball' },
    { name: 'Trae Young', sport: 'Basketball' },
    { name: 'Donovan Mitchell', sport: 'Basketball' },
    { name: 'Ja Morant', sport: 'Basketball' },
    { name: 'Zion Williamson', sport: 'Basketball' },
    { name: 'Karl-Anthony Towns', sport: 'Basketball' },
    { name: 'Kawhi Leonard', sport: 'Basketball' },
    { name: 'Joel Embiid', sport: 'Basketball' },
    { name: 'Anthony Davis', sport: 'Basketball' },
    { name: 'Kyrie Irving', sport: 'Basketball' },
    { name: 'Franz Wagner', sport: 'Basketball' },
    { name: 'Tyler Herro', sport: 'Basketball' },
    { name: 'De\'Aaron Fox', sport: 'Basketball' },
    { name: 'Zach LaVine', sport: 'Basketball' },
    { name: 'James Harden', sport: 'Basketball' },
    { name: 'DeMar DeRozan', sport: 'Basketball' },
    { name: 'Jaylen Brown', sport: 'Basketball' },
    { name: 'Jaren Jackson Jr.', sport: 'Basketball' },
    { name: 'Norman Powell', sport: 'Basketball' },
    { name: 'Jalen Williams', sport: 'Basketball' },
    { name: 'Jamal Murray', sport: 'Basketball' },
    { name: 'RJ Barrett', sport: 'Basketball' },
    { name: 'Jalen Green', sport: 'Basketball' },
    { name: 'Darius Garland', sport: 'Basketball' },
    { name: 'Jordan Poole', sport: 'Basketball' },
    { name: 'Coby White', sport: 'Basketball' },
    { name: 'Miles Bridges', sport: 'Basketball' },
    { name: 'Pascal Siakam', sport: 'Basketball' },
    { name: 'Austin Reaves', sport: 'Basketball' },
    { name: 'Scottie Barnes', sport: 'Basketball' },
    { name: 'Anfernee Simons', sport: 'Basketball' },
    { name: 'Desmond Bane', sport: 'Basketball' },
    { name: 'Domantas Sabonis', sport: 'Basketball' },
    { name: 'Alperen Sengun', sport: 'Basketball' },
    { name: 'Julius Randle', sport: 'Basketball' },
    { name: 'Tyrese Haliburton', sport: 'Basketball' },
    { name: 'Shaedon Sharpe', sport: 'Basketball' },
    { name: 'Evan Mobley', sport: 'Basketball' },
    { name: 'Nikola Vučević', sport: 'Basketball' },
    { name: 'Collin Sexton', sport: 'Basketball' },
    { name: 'Michael Porter Jr.', sport: 'Basketball' },
    { name: 'Bam Adebayo', sport: 'Basketball' },
    { name: 'OG Anunoby', sport: 'Basketball' },
    { name: 'Andrew Wiggins', sport: 'Basketball' },
    { name: 'Mikal Bridges', sport: 'Basketball' },
    { name: 'Tyrese Maxey', sport: 'Basketball' },
    { name: 'Lauri Markkanen', sport: 'Basketball' },
    { name: 'Deni Avdija', sport: 'Basketball' },
    { name: 'Keyonte George', sport: 'Basketball' },
    { name: 'Jalen Johnson', sport: 'Basketball' },
    { name: 'Brandon Ingram', sport: 'Basketball' },
    { name: 'Paolo Banchero', sport: 'Basketball' },
    { name: 'Trey Murphy III', sport: 'Basketball' },
    { name: 'Dillon Brooks', sport: 'Basketball' },
    { name: 'Nickeil Alexander-Walker', sport: 'Basketball' },
    { name: 'Jimmy Butler III', sport: 'Basketball' },
    { name: 'Cooper Flagg', sport: 'Basketball' },
    { name: 'LaMelo Ball', sport: 'Basketball' },
    { name: 'Kon Knueppel', sport: 'Basketball' },
    { name: 'CJ McCollum', sport: 'Basketball' },
    { name: 'Amen Thompson', sport: 'Basketball' },
    { name: 'Jalen Duren', sport: 'Basketball' },
    { name: 'Chet Holmgren', sport: 'Basketball' },
    { name: 'Andrew Nembhard', sport: 'Basketball' },
    { name: 'VJ Edgecombe', sport: 'Basketball' },
    { name: 'Cedric Coward', sport: 'Basketball' },
    { name: 'Jeremiah Fears', sport: 'Basketball' },
    { name: 'Tre Johnson', sport: 'Basketball' },
    { name: 'Derik Queen', sport: 'Basketball' },
    { name: 'Ace Bailey', sport: 'Basketball' },
    { name: 'Caleb Love', sport: 'Basketball' },
    { name: 'Egor Dëmin', sport: 'Basketball' },
    { name: 'Dylan Harper', sport: 'Basketball' },
    { name: 'Maxime Raynaud', sport: 'Basketball' },
    { name: 'Ryan Kalkbrenner', sport: 'Basketball' },
    { name: 'Danny Wolf', sport: 'Basketball' },
    { name: 'Collin Murray-Boyles', sport: 'Basketball' },
    { name: 'Will Richard', sport: 'Basketball' },
    { name: 'Kobe Sanders', sport: 'Basketball' },
    { name: 'Ryan Nembhard', sport: 'Basketball' },
    { name: 'Walter Clayton Jr.', sport: 'Basketball' },
    { name: 'Drake Powell', sport: 'Basketball' },
    { name: 'Brandon Miller', sport: 'Basketball' },
    { name: 'GG Jackson', sport: 'Basketball' },
    { name: 'Scoot Henderson', sport: 'Basketball' },
    { name: 'Cam Whitmore', sport: 'Basketball' },
    { name: 'Jaime Jaquez Jr.', sport: 'Basketball' },
    { name: 'Brandin Podziemski', sport: 'Basketball' },
    { name: 'Duop Reath', sport: 'Basketball' },
    { name: 'Ausar Thompson', sport: 'Basketball' },
    { name: 'Dereck Lively II', sport: 'Basketball' },
    { name: 'Gradey Dick', sport: 'Basketball' },
    { name: 'Bilal Coulibaly', sport: 'Basketball' },
    { name: 'Marcus Sasser', sport: 'Basketball' },
    { name: 'Trayce Jackson-Davis', sport: 'Basketball' },
    { name: 'Jordan Hawkins', sport: 'Basketball' },
    { name: 'Brice Sensabaugh', sport: 'Basketball' },
    { name: 'Toumani Camara', sport: 'Basketball' },
    { name: 'Taylor Hendricks', sport: 'Basketball' },
    { name: 'Vasilije Micic', sport: 'Basketball' },
    { name: 'Cason Wallace', sport: 'Basketball' },
    { name: 'Kris Murray', sport: 'Basketball' },
    { name: 'Nick Smith Jr.', sport: 'Basketball' },
    { name: 'Craig Porter Jr.', sport: 'Basketball' },
    { name: 'Ricky Council IV', sport: 'Basketball' },
    { name: 'Sasha Vezenkov', sport: 'Basketball' },
    { name: 'Jalen Wilson', sport: 'Basketball' },
    { name: 'Anthony Black', sport: 'Basketball' },
    { name: 'Julian Strawther', sport: 'Basketball' },
    { name: 'Ben Sheppard', sport: 'Basketball' },
    { name: 'Rayan Rupert', sport: 'Basketball' },
    { name: 'Jarace Walker', sport: 'Basketball' },
    { name: 'Olivier-Maxence Prosper', sport: 'Basketball' },
    { name: 'Julian Phillips', sport: 'Basketball' },
    { name: 'Andre Jackson Jr.', sport: 'Basketball' },
    { name: 'Colby Jones', sport: 'Basketball' },
    { name: 'Kobe Brown', sport: 'Basketball' },
    { name: 'Maxwell Lewis', sport: 'Basketball' },
    { name: 'Paul George', sport: 'Basketball' },
    { name: 'Dejounte Murray', sport: 'Basketball' },
    { name: 'Cam Thomas', sport: 'Basketball' },
    { name: 'Kyle Kuzma', sport: 'Basketball' },
    { name: 'Terry Rozier', sport: 'Basketball' },
    { name: 'Devin Vassell', sport: 'Basketball' },
    { name: 'Kristaps Porziņģis', sport: 'Basketball' },
    { name: 'Keldon Johnson', sport: 'Basketball' },
    { name: 'Klay Thompson', sport: 'Basketball' },
    { name: 'Bojan Bogdanovic', sport: 'Basketball' },
    { name: 'Jordan Clarkson', sport: 'Basketball' },
    { name: 'Jerami Grant', sport: 'Basketball' },
    { name: 'Fred VanVleet', sport: 'Basketball' },
    { name: 'Jrue Holiday', sport: 'Basketball' },
    { name: 'Kevin Porter Jr.', sport: 'Basketball' },
    { name: 'Khris Middleton', sport: 'Basketball' },
    { name: 'Russell Westbrook', sport: 'Basketball' },
    { name: 'Gary Trent Jr.', sport: 'Basketball' },
    { name: 'D\'Angelo Russell', sport: 'Basketball' },
    { name: 'Christian Wood', sport: 'Basketball' },
    { name: 'Jonas Valančiūnas', sport: 'Basketball' },
    { name: 'Tobias Harris', sport: 'Basketball' },
    { name: 'Deandre Ayton', sport: 'Basketball' },
    { name: 'Caris LeVert', sport: 'Basketball' },
    { name: 'Reggie Jackson', sport: 'Basketball' },
    { name: 'Harrison Barnes', sport: 'Basketball' },
    // 2024-25 Rookies





    { name: 'Stephon Castle', sport: 'Basketball' },
    { name: 'Alex Sarr', sport: 'Basketball' },
    { name: 'Zaccharie Risacher', sport: 'Basketball' },
    { name: 'Jaylen Wells', sport: 'Basketball' },
    { name: 'Justin Edwards', sport: 'Basketball' },
    { name: 'Bub Carrington', sport: 'Basketball' },
    { name: 'Kyle Filipowski', sport: 'Basketball' },
    { name: 'Kel\'el Ware', sport: 'Basketball' },
    { name: 'Zach Edey', sport: 'Basketball' },
    { name: 'Yves Missi', sport: 'Basketball' },
    { name: 'Dalton Knecht', sport: 'Basketball' },
    { name: 'Kyshawn George', sport: 'Basketball' },
    { name: 'Isaiah Collier', sport: 'Basketball' },
    { name: 'Ja\'Kobe Walter', sport: 'Basketball' },
    { name: 'Matas Buzelis', sport: 'Basketball' },
    { name: 'Quinten Post', sport: 'Basketball' },
    { name: 'KJ Simpson', sport: 'Basketball' },
    { name: 'Karlo Matković', sport: 'Basketball' },
    { name: 'AJ Johnson', sport: 'Basketball' },
    { name: 'Tristan da Silva', sport: 'Basketball' },
    { name: 'Jamal Shead', sport: 'Basketball' },
    { name: 'Jamison Battle', sport: 'Basketball' },
    { name: 'Antonio Reeves', sport: 'Basketball' },
    { name: 'Ryan Dunn', sport: 'Basketball' },
    { name: 'Donovan Clingan', sport: 'Basketball' },
    { name: 'Ajay Mitchell', sport: 'Basketball' },
    { name: 'Ronald Holland II', sport: 'Basketball' },
    { name: 'Jonathan Mogbo', sport: 'Basketball' },
    { name: 'Tidjane Salaün', sport: 'Basketball' },
    { name: 'Adem Bona', sport: 'Basketball' },
    { name: 'Tom Brady', sport: 'Football' },
    { name: 'Patrick Mahomes', sport: 'Football' },
    { name: 'Mike Trout', sport: 'Baseball' },
    { name: 'Shohei Ohtani', sport: 'Baseball' },
    { name: 'Lionel Messi', sport: 'Soccer' },
    { name: 'Cristiano Ronaldo', sport: 'Soccer' },

    // Pokemon - The "Big Three" & Absolute Top Tier
    { name: 'Charizard', sport: 'Pokemon' },
    { name: 'Pikachu', sport: 'Pokemon' },
    { name: 'Umbreon', sport: 'Pokemon' },
    { name: 'Rayquaza', sport: 'Pokemon' },
    { name: 'Lugia', sport: 'Pokemon' },
    // Gen 1 Favorites & Starters
    { name: 'Blastoise', sport: 'Pokemon' },
    { name: 'Venusaur', sport: 'Pokemon' },
    { name: 'Mewtwo', sport: 'Pokemon' },
    { name: 'Mew', sport: 'Pokemon' },
    { name: 'Gengar', sport: 'Pokemon' },
    { name: 'Arcanine', sport: 'Pokemon' },
    { name: 'Dragonite', sport: 'Pokemon' },
    { name: 'Eevee', sport: 'Pokemon' },
    { name: 'Gyarados', sport: 'Pokemon' },
    { name: 'Alakazam', sport: 'Pokemon' },
    { name: 'Machamp', sport: 'Pokemon' },
    { name: 'Snorlax', sport: 'Pokemon' },
    { name: 'Dragonair', sport: 'Pokemon' },
    // Popular "Eeeveelutions" & Gen 2
    { name: 'Espeon', sport: 'Pokemon' },
    { name: 'Sylveon', sport: 'Pokemon' },
    { name: 'Vaporeon', sport: 'Pokemon' },
    { name: 'Flareon', sport: 'Pokemon' },
    { name: 'Jolteon', sport: 'Pokemon' },
    { name: 'Leafeon', sport: 'Pokemon' },
    { name: 'Glaceon', sport: 'Pokemon' },
    { name: 'Tyranitar', sport: 'Pokemon' },
    { name: 'Celebi', sport: 'Pokemon' },
    // Legendary & Mythical Pokemon
    { name: 'Giratina', sport: 'Pokemon' },
    { name: 'Latias', sport: 'Pokemon' },
    { name: 'Latios', sport: 'Pokemon' },
    { name: 'Kyogre', sport: 'Pokemon' },
    { name: 'Groudon', sport: 'Pokemon' },
    { name: 'Deoxys', sport: 'Pokemon' },
    { name: 'Darkrai', sport: 'Pokemon' },
    { name: 'Arceus', sport: 'Pokemon' },
    { name: 'Dialga', sport: 'Pokemon' },
    { name: 'Palkia', sport: 'Pokemon' },
    { name: 'Ho-Oh', sport: 'Pokemon' },
    // Modern & Fan-Favorite Collectibles
    { name: 'Greninja', sport: 'Pokemon' },
    { name: 'Lucario', sport: 'Pokemon' },
    { name: 'Gardevoir', sport: 'Pokemon' },
    { name: 'Mimikyu', sport: 'Pokemon' },
    { name: 'Zoroark', sport: 'Pokemon' },
    { name: 'Garchomp', sport: 'Pokemon' },
    { name: 'Metagross', sport: 'Pokemon' },
    { name: 'Hydreigon', sport: 'Pokemon' },
    { name: 'Togepi', sport: 'Pokemon' },
    { name: 'Scizor', sport: 'Pokemon' },
];

export interface ScanHistoryItem {
    id: string;
    name: string;
    isKeeper: boolean;
    isPrizmRookie?: boolean;
    brand?: string;
    cardType?: string;
    sport?: string;
    cardYear?: number | null;
    salesData?: {
        averagePrice?: number | null;
        salesCount?: number | null;
        source?: string | null;
    };
    timestamp: Date;
    imageDataUri?: string;
}
