
export type Player = {
  name: string;
  sport: "MLB" | "NBA" | "NHL" | "NFL" | "Soccer" | "Pokemon" | "WWE" | "Uncategorized";
  prizmRookieYear?: number;
};

// Players with valuable Prizm rookie cards
const prizmRookies: Player[] = [
    // 2017
    { name: "Patrick Mahomes", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Deshaun Watson", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Christian McCaffrey", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Alvin Kamara", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Donovan Mitchell", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Jayson Tatum", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Aaron Judge", sport: "MLB", prizmRookieYear: 2017 },
    { name: "Kareem Hunt", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Cody Bellinger", sport: "MLB", prizmRookieYear: 2017 },
    { name: "Ben Simmons", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Kylian Mbappé", sport: "Soccer", prizmRookieYear: 2017 },
    { name: "Connor McDavid", sport: "NHL", prizmRookieYear: 2017 },
    { name: "De'Aaron Fox", sport: "NBA", prizmRookieYear: 2017 },
    { name: "John Collins", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Josh Allen", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Lonzo Ball", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Andrew Benintendi", sport: "MLB", prizmRookieYear: 2017 },
    { name: "T.J. Watt", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Lauri Markkanen", sport: "NBA", prizmRookieYear: 2017 },
    { name: "JuJu Smith-Schuster", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Mitch Trubisky", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Derek Carr", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Dalvin Cook", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Kyle Kuzma", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Josh Jackson", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Dennis Smith Jr.", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Malik Monk", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Bam Adebayo", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Jonathan Isaac", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Luke Kennard", sport: "NBA", prizmRookieYear: 2017 },
    { name: "Leonard Fournette", sport: "NFL", prizmRookieYear: 2017 },
    { name: "Chris Godwin", sport: "NFL", prizmRookieYear: 2017 },

    // 2018
    { name: "Luka Dončić", sport: "NBA", prizmRookieYear: 2018 },
    { name: "Trae Young", sport: "NBA", prizmRookieYear: 2018 },
    { name: "Shohei Ohtani", sport: "MLB", prizmRookieYear: 2018 },
    { name: "Ronald Acuña Jr.", sport: "MLB", prizmRookieYear: 2018 },
    { name: "Baker Mayfield", sport: "NFL", prizmRookieYear: 2018 },
    { name: "Saquon Barkley", sport: "NFL", prizmRookieYear: 2018 },
    { name: "Juan Soto", sport: "MLB", prizmRookieYear: 2018 },
    { name: "Deandre Ayton", sport: "NBA", prizmRookieYear: 2018 },
    { name: "Darius Leonard", sport: "NFL", prizmRookieYear: 2018 },
    { name: "Jaren Jackson Jr.", sport: "NBA", prizmRookieYear: 2018 },
    { name: "Matthijs de Ligt", sport: "Soccer", prizmRookieYear: 2018 },
    { name: "Jadon Sancho", sport: "Soccer", prizmRookieYear: 2018 },
    { name: "Vinicius Jr.", sport: "Soccer", prizmRookieYear: 2018 },
    { name: "Trent Alexander-Arnold", sport: "Soccer", prizmRookieYear: 2018 },
    { name: "Kai Havertz", sport: "Soccer", prizmRookieYear: 2018 },
    { name: "Shai Gilgeous-Alexander", sport: "NBA", prizmRookieYear: 2018 },
    { name: "Gleyber Torres", sport: "MLB", prizmRookieYear: 2018 },
    { name: "Miguel Andújar", sport: "MLB", prizmRookieYear: 2018 },
    { name: "Nick Chubb", sport: "NFL", prizmRookieYear: 2018 },
    { name: "Bradley Chubb", sport: "NFL", prizmRookieYear: 2018 },

    // 2019
    { name: "Zion Williamson", sport: "NBA", prizmRookieYear: 2019 },
    { name: "Ja Morant", sport: "NBA", prizmRookieYear: 2019 },
    { name: "Kyler Murray", sport: "NFL", prizmRookieYear: 2019 },
    { name: "Nick Bosa", sport: "NFL", prizmRookieYear: 2019 },
    { name: "Fernando Tatis Jr.", sport: "MLB", prizmRookieYear: 2019 },
    { name: "Pete Alonso", sport: "MLB", prizmRookieYear: 2019 },
    { name: "Josh Jacobs", sport: "NFL", prizmRookieYear: 2019 },
    { name: "RJ Barrett", sport: "NBA", prizmRookieYear: 2019 },
    { name: "A.J. Brown", sport: "NFL", prizmRookieYear: 2019 },
    { name: "Yordan Alvarez", sport: "MLB", prizmRookieYear: 2019 },
    { name: "Devin Bush", sport: "NFL", prizmRookieYear: 2019 },
    { name: "Kendrick Nunn", sport: "NBA", prizmRookieYear: 2019 },
    { name: "Brandon Clarke", sport: "NBA", prizmRookieYear: 2019 },
    { name: "Mike Soroka", sport: "MLB", prizmRookieYear: 2019 },
    { name: "Bryan Reynolds", sport: "MLB", prizmRookieYear: 2019 },

    // 2020
    { name: "Justin Herbert", sport: "NFL", prizmRookieYear: 2020 },
    { name: "Joe Burrow", sport: "NFL", prizmRookieYear: 2020 },
    { name: "Anthony Edwards", sport: "NBA", prizmRookieYear: 2020 },
    { name: "LaMelo Ball", sport: "NBA", prizmRookieYear: 2020 },
    { name: "Justin Jefferson", sport: "NFL", prizmRookieYear: 2020 },
    { name: "Chase Young", sport: "NFL", prizmRookieYear: 2020 },
    { name: "Jonathan Taylor", sport: "NFL", prizmRookieYear: 2020 },
    { name: "Tyrese Haliburton", sport: "NBA", prizmRookieYear: 2020 },
    { name: "Ke’Bryan Hayes", sport: "MLB", prizmRookieYear: 2020 },
    { name: "Desmond Bane", sport: "NBA", prizmRookieYear: 2020 },
    { name: "Erling Haaland", sport: "Soccer", prizmRookieYear: 2020 },
    { name: "Ansu Fati", sport: "Soccer", prizmRookieYear: 2020 },
    { name: "Phil Foden", sport: "Soccer", prizmRookieYear: 2020 },
    { name: "Alphonso Davies", sport: "Soccer", prizmRookieYear: 2020 },
    { name: "Mason Greenwood", sport: "Soccer", prizmRookieYear: 2020 },
    { name: "Immanuel Quickley", sport: "NBA", prizmRookieYear: 2020 },
    { name: "Devin Williams", sport: "MLB", prizmRookieYear: 2020 },
    { name: "Kyle Lewis", sport: "MLB", prizmRookieYear: 2020 },
    { name: "Alec Bohm", sport: "MLB", prizmRookieYear: 2020 },
    { name: "Jake Cronenworth", sport: "MLB", prizmRookieYear: 2020 },
    { name: "Luis Robert", sport: "MLB", prizmRookieYear: 2020 },
    { name: "Pedri", sport: "Soccer", prizmRookieYear: 2020 },
    { name: "Jude Bellingham", sport: "Soccer", prizmRookieYear: 2020 },
    { name: "Mason Mount", sport: "Soccer", prizmRookieYear: 2020 },
    { name: "João Félix", sport: "Soccer", prizmRookieYear: 2020 },

    // 2021
    { name: "Trevor Lawrence", sport: "NFL", prizmRookieYear: 2021 },
    { name: "Ja’Marr Chase", sport: "NFL", prizmRookieYear: 2021 },
    { name: "Mac Jones", sport: "NFL", prizmRookieYear: 2021 },
    { name: "Cade Cunningham", sport: "NBA", prizmRookieYear: 2021 },
    { name: "Evan Mobley", sport: "NBA", prizmRookieYear: 2021 },
    { name: "Scottie Barnes", sport: "NBA", prizmRookieYear: 2021 },
    { name: "Micah Parsons", sport: "NFL", prizmRookieYear: 2021 },
    { name: "Wander Franco", sport: "MLB", prizmRookieYear: 2021 },
    { name: "Jonathan India", sport: "MLB", prizmRookieYear: 2021 },
    { name: "Najee Harris", sport: "NFL", prizmRookieYear: 2021 },
    { name: "Kyle Pitts", sport: "NFL", prizmRookieYear: 2021 },
    { name: "Josh Giddey", sport: "NBA", prizmRookieYear: 2021 },
    { name: "Randy Arozarena", sport: "MLB", prizmRookieYear: 2021 },
    { name: "Adolis García", sport: "MLB", prizmRookieYear: 2021 },
    { name: "Ryan Mountcastle", sport: "MLB", prizmRookieYear: 2021 },
    { name: "Florian Wirtz", sport: "Soccer", prizmRookieYear: 2021 },
    { name: "Gavi", sport: "Soccer", prizmRookieYear: 2021 },
    { name: "Bukayo Saka", sport: "Soccer", prizmRookieYear: 2021 },

    // 2022
    { name: "Brock Purdy", sport: "NFL", prizmRookieYear: 2022 },
    { name: "Paolo Banchero", sport: "NBA", prizmRookieYear: 2022 },
    { name: "Julio Rodríguez", sport: "MLB", prizmRookieYear: 2022 },
    { name: "Kenny Pickett", sport: "NFL", prizmRookieYear: 2022 },
    { name: "Jalen Williams", sport: "NBA", prizmRookieYear: 2022 },
    { name: "Garrett Wilson", sport: "NFL", prizmRookieYear: 2022 },
    { name: "Sauce Gardner", sport: "NFL", prizmRookieYear: 2022 },
    { name: "Bennedict Mathurin", sport: "NBA", prizmRookieYear: 2022 },
    { name: "Adley Rutschman", sport: "MLB", prizmRookieYear: 2022 },
    { name: "Keegan Murray", sport: "NBA", prizmRookieYear: 2022 },
    { name: "Kenneth Walker III", sport: "NFL", prizmRookieYear: 2022 },
    { name: "Chris Olave", sport: "NFL", prizmRookieYear: 2022 },
    { name: "Walker Kessler", sport: "NBA", prizmRookieYear: 2022 },
    { name: "Michael Harris II", sport: "MLB", prizmRookieYear: 2022 },
    { name: "Bobby Witt Jr.", sport: "MLB", prizmRookieYear: 2022 },
    { name: "Spencer Strider", sport: "MLB", prizmRookieYear: 2022 },
    { name: "Jamal Musiala", sport: "Soccer", prizmRookieYear: 2022 },
    { name: "Eduardo Camavinga", sport: "Soccer", prizmRookieYear: 2022 },
    { name: "Khvicha Kvaratskhelia", sport: "Soccer", prizmRookieYear: 2022 },

    // 2023
    { name: "C.J. Stroud", sport: "NFL", prizmRookieYear: 2023 },
    { name: "Victor Wembanyama", sport: "NBA", prizmRookieYear: 2023 },
    { name: "Anthony Richardson", sport: "NFL", prizmRookieYear: 2023 },
    { name: "Puka Nacua", sport: "NFL", prizmRookieYear: 2023 },
    { name: "Bryce Young", sport: "NFL", prizmRookieYear: 2023 },
    { name: "Chet Holmgren", "sport": "NBA", prizmRookieYear: 2023 },
    { name: "Brandon Miller", sport: "NBA", prizmRookieYear: 2023 },
    { name: "Bijan Robinson", sport: "NFL", prizmRookieYear: 2023 },
    { name: "Gunnar Henderson", sport: "MLB", prizmRookieYear: 2023 },
    { name: "Corbin Carroll", sport: "MLB", prizmRookieYear: 2023 },
    { name: "Will Anderson Jr.", sport: "NFL", prizmRookieYear: 2023 },
    { name: "Jahmyr Gibbs", sport: "NFL", prizmRookieYear: 2023 },
    { name: "Sam LaPorta", sport: "NFL", prizmRookieYear: 2023 },
    { name: "Jaime Jaquez Jr.", sport: "NBA", prizmRookieYear: 2023 },
    { name: "Dereck Lively II", sport: "NBA", prizmRookieYear: 2023 },
    { name: "Kodai Senga", sport: "MLB", prizmRookieYear: 2023 },
    { name: "Josh Jung", sport: "MLB", prizmRookieYear: 2023 },
    { name: "Francisco Álvarez", sport: "MLB", prizmRookieYear: 2023 },
    { name: "Rasmus Højlund", sport: "Soccer", prizmRookieYear: 2023 },
    { name: "Alejandro Garnacho", sport: "Soccer", prizmRookieYear: 2023 },
    { name: "Lamine Yamal", sport: "Soccer", prizmRookieYear: 2023 },
    { name: "Warren Zaïre-Emery", sport: "Soccer", prizmRookieYear: 2023 },
];

const otherPlayers: Player[] = [
    {"name": "Aaron Donald", "sport": "NFL"},
    {"name": "Abomasnow", "sport": "Pokemon"},
    {"name": "Absol", "sport": "Pokemon"},
    {"name": "Accelgor", "sport": "Pokemon"},
    {"name": "Achraf Hakimi", "sport": "Soccer"},
    {"name": "Adama Traoré", "sport": "Soccer"},
    {"name": "Adolis Garcia", "sport": "MLB"},
    {"name": "Aggron", "sport": "Pokemon"},
    {"name": "Aidan Hutchinson", "sport": "NFL"},
    {"name": "AJ Pollock", "sport": "MLB"},
    {"name": "AJ Styles", "sport": "WWE"},
    {"name": "Al Horford", "sport": "NBA"},
    {"name": "Al Jefferson", "sport": "NBA"},
    {"name": "Alakazam", "sport": "Pokemon"},
    {"name": "Alejandro Balde", "sport": "Soccer"},
    {"name": "Alejandro Kirk", "sport": "MLB"},
    {"name": "Alek Manoah", "sport": "MLB"},
    {"name": "Alessandro Del Piero", "sport": "Soccer"},
    {"name": "Alessandro Nesta", "sport": "Soccer"},
    {"name": "Alex Bregman", "sport": "MLB"},
    {"name": "Alex Caruso", "sport": "NBA"},
    {"name": "Alex Verdugo", "sport": "MLB"},
    {"name": "Alexa Bliss", "sport": "WWE"},
    {"name": "Alexis Sánchez", "sport": "Soccer"},
    {"name": "Alfredo Di Stéfano", "sport": "Soccer"},
    {"name": "Alisson Becker", "sport": "Soccer"},
    {"name": "Alomomola", "sport": "Pokemon"},
    {"name": "Alperen Sengun", "sport": "NBA"},
    {"name": "Altaria", "sport": "Pokemon"},
    {"name": "Amoonguss", "sport": "Pokemon"},
    {"name": "Andre Drummond", "sport": "NBA"},
    {"name": "Andre Iguodala", "sport": "NBA"},
    {"name": "André the Giant", "sport": "WWE"},
    {"name": "Andrea Pirlo", "sport": "Soccer"},
    {"name": "Andrew Robertson", "sport": "Soccer"},
    {"name": "Andrew Van Ginkel", "sport": "NFL"},
    {"name": "Andrew Wiggins", "sport": "NBA"},
    {"name": "Andrei Vasilevskiy", "sport": "NHL"},
    {"name": "Andrés Giménez", "sport": "MLB"},
    {"name": "Andrés Iniesta", "sport": "Soccer"},
    {"name": "Andriy Shevchenko", "sport": "Soccer"},
    {"name": "Anfernee Simons", "sport": "NBA"},
    {"name": "Angelo Dawkins", "sport": "WWE"},
    {"name": "Anthony Davis", "sport": "NBA"},
    {"name": "Anthony Martial", "sport": "Soccer"},
    {"name": "Anthony Rendon", "sport": "MLB"},
    {"name": "Anthony Rizzo", "sport": "MLB"},
    {"name": "Anthony Volpe", "sport": "MLB"},
    {"name": "Antoine Griezmann", "sport": "Soccer"},
    {"name": "Antoine Winfield Jr.", "sport": "NFL"},
    {"name": "Arcanine", "sport": "Pokemon"},
    {"name": "Archeops", "sport": "Pokemon"},
    {"name": "Arceus", "sport": "Pokemon"},
    {"name": "Arda Güler", "sport": "Soccer"},
    {"name": "Arjen Robben", "sport": "Soccer"},
    {"name": "Articuno", "sport": "Pokemon"},
    {"name": "Artemi Panarin", "sport": "NHL"},
    {"name": "Arturo Vidal", "sport": "Soccer"},
    {"name": "Asuka", "sport": "WWE"},
    {"name": "Audino", "sport": "Pokemon"},
    {"name": "Aurélien Tchouaméni", "sport": "Soccer"},
    {"name": "Austin Meadows", "sport": "MLB"},
    {"name": "Austin Reaves", "sport": "NBA"},
    {"name": "Austin Riley", "sport": "MLB"},
    {"name": "Auston Matthews", "sport": "NHL"},
    {"name": "Ángel Di María", "sport": "Soccer"},
    {"name": "Babe Ruth", "sport": "MLB"},
    {"name": "Banette", "sport": "Pokemon"},
    {"name": "Barry Sanders", "sport": "NFL"},
    {"name": "Basculin", "sport": "Pokemon"},
    {"name": "Bastian Schweinsteiger", "sport": "Soccer"},
    {"name": "Batista", "sport": "WWE"},
    {"name": "Bayley", "sport": "WWE"},
    {"name": "Beartic", "sport": "Pokemon"},
    {"name": "Becky Lynch", "sport": "WWE"},
    {"name": "Beheeyem", "sport": "Pokemon"},
    {"name": "Bernardo Silva", "sport": "Soccer"},
    {"name": "Bianca Belair", "sport": "WWE"},
    {"name": "Big E", "sport": "WWE"},
    {"name": "Bisharp", "sport": "Pokemon"},
    {"name": "Blake Griffin", "sport": "NBA"},
    {"name": "Blake Snell", "sport": "MLB"},
    {"name": "Blastoise", "sport": "Pokemon"},
    {"name": "Blaziken", "sport": "Pokemon"},
    {"name": "Bo Bichette", "sport": "MLB"},
    {"name": "Bo Nix", "sport": "NFL"},
    {"name": "Bobby Charlton", "sport": "Soccer"},
    {"name": "Bobby Dalbec", "sport": "MLB"},
    {"name": "Bobby Lashley", "sport": "WWE"},
    {"name": "Bobby Wagner", "sport": "NFL"},
    {"name": "Bogdan Bogdanović", "sport": "NBA"},
    {"name": "Bojan Bogdanović", "sport": "NBA"},
    {"name": "Borja Iglesias", "sport": "Soccer"},
    {"name": "Bouffalant", "sport": "Pokemon"},
    {"name": "Brad Marchand", "sport": "NHL"},
    {"name": "Braun Strowman", "sport": "WWE"},
    {"name": "Braviary", "sport": "Pokemon"},
    {"name": "Bray Wyatt", "sport": "WWE"},
    {"name": "Brendan Donovan", "sport": "MLB"},
    {"name": "Bret Hart", "sport": "WWE"},
    {"name": "Brett Baty", "sport": "MLB"},
    {"name": "Brett Favre", "sport": "NFL"},
    {"name": "Brian Thomas Jr.", "sport": "NFL"},
    {"name": "Brook Lopez", "sport": "NBA"},
    {"name": "Brooks Lee", "sport": "MLB"},
    {"name": "Bruno Fernandes", "sport": "Soccer"},
    {"name": "Bryn Forbes", "sport": "NBA"},
    {"name": "Bryson Stott", "sport": "MLB"},
    {"name": "Budda Baker", "sport": "NFL"},
    {"name": "Buddy Hield", "sport": "NBA"},
    {"name": "Byron Buxton", "sport": "MLB"},
    {"name": "Cale Makar", "sport": "NHL"},
    {"name": "Cam Thomas", "sport": "NBA"},
    {"name": "Cameron Heyward", "sport": "NFL"},
    {"name": "Cameron Payne", "sport": "NBA"},
    {"name": "Camilo Doval", "sport": "MLB"},
    {"name": "Carles Puyol", "sport": "Soccer"},
    {"name": "Carlos Correa", "sport": "MLB"},
    {"name": "Carmela", "sport": "WWE"},
    {"name": "Carmelo Anthony", "sport": "NBA"},
    {"name": "Carracosta", "sport": "Pokemon"},
    {"name": "Caris LeVert", "sport": "NBA"},
    {"name": "Casemiro", "sport": "Soccer"},
    {"name": "CeeDee Lamb", "sport": "NFL"},
    {"name": "Cedric Mullins", "sport": "MLB"},
    {"name": "Celebi", "sport": "Pokemon"},
    {"name": "Chandelure", "sport": "Pokemon"},
    {"name": "Charles Barkley", "sport": "NBA"},
    {"name": "Charizard", "sport": "Pokemon"},
    {"name": "Charlotte Flair", "sport": "WWE"},
    {"name": "Chris Jericho", "sport": "WWE"},
    {"name": "Chris Jones", "sport": "NFL"},
    {"name": "Chris Lindstrom", "sport": "NFL"},
    {"name": "Chris Paul", "sport": "NBA"},
    {"name": "Christian Eriksen", "sport": "Soccer"},
    {"name": "Christian Gonzalez", "sport": "NFL"},
    {"name": "Christian Pulisic", "sport": "Soccer"},
    {"name": "Christian Vázquez", "sport": "MLB"},
    {"name": "Christian Watson", "sport": "NFL"},
    {"name": "Christian Wilkins", "sport": "NFL"},
    {"name": "Cinccino", "sport": "Pokemon"},
    {"name": "Ciro Immobile", "sport": "Soccer"},
    {"name": "C.J. Cron", "sport": "MLB"},
    {"name": "Clayton Kershaw", "sport": "MLB"},
    {"name": "Clint Capela", "sport": "NBA"},
    {"name": "Cobalion", "sport": "Pokemon"},
    {"name": "Cody Rhodes", "sport": "WWE"},
    {"name": "Cofagrigus", "sport": "Pokemon"},
    {"name": "Cole Anthony", "sport": "NBA"},
    {"name": "Collin Sexton", "sport": "NBA"},
    {"name": "Colton Cowser", "sport": "MLB"},
    {"name": "Conkeldurr", "sport": "Pokemon"},
    {"name": "Cooper DeJean", "sport": "NFL"},
    {"name": "Cooper Kupp", "sport": "NFL"},
    {"name": "Corbin Burnes", "sport": "MLB"},
    {"name": "Corey Seager", "sport": "MLB"},
    {"name": "Creed Humphrey", "sport": "NFL"},
    {"name": "Cresselia", "sport": "Pokemon"},
    {"name": "Cristian Javier", "sport": "MLB"},
    {"name": "Cristiano Ronaldo", "sport": "Soccer"},
    {"name": "Crustle", "sport": "Pokemon"},
    {"name": "Cryogonal", "sport": "Pokemon"},
    {"name": "Curtis Mead", "sport": "MLB"},
    {"name": "Cy Young", "sport": "MLB"},
    {"name": "Dak Prescott", "sport": "NFL"},
    {"name": "Damian Lillard", "sport": "NBA"},
    {"name": "Damian Priest", "sport": "WWE"},
    {"name": "Dan Marino", "sport": "NFL"},
    {"name": "Daniel Bryan", "sport": "WWE"},
    {"name": "Daniel Gafford", "sport": "NBA"},
    {"name": "Danielle Hunter", "sport": "NFL"},
    {"name": "Danilo Gallinari", "sport": "NBA"},
    {"name": "Dani Alves", "sport": "Soccer"},
    {"name": "Danny Green", "sport": "NBA"},
    {"name": "Dansby Swanson", "sport": "MLB"},
    {"name": "Dario Saric", "sport": "NBA"},
    {"name": "Darkrai", "sport": "Pokemon"},
    {"name": "Darmanitan", "sport": "Pokemon"},
    {"name": "DaRon Bland", "sport": "NFL"},
    {"name": "Daulton Varsho", "sport": "MLB"},
    {"name": "Davante Adams", "sport": "NFL"},
    {"name": "David Beckham", "sport": "Soccer"},
    {"name": "David Pastrňák", "sport": "NHL"},
    {"name": "David Silva", "sport": "Soccer"},
    {"name": "Davis Bertāns", "sport": "NBA"},
    {"name": "Deebo Samuel", "sport": "NFL"},
    {"name": "Deion Sanders", "sport": "NFL"},
    {"name": "Dejan Kulusevski", "sport": "Soccer"},
    {"name": "Dejounte Murray", "sport": "NBA"},
    {"name": "Dele Alli", "sport": "Soccer"},
    {"name": "Delon Wright", "sport": "NBA"},
    {"name": "DeMarcus Cousins", "sport": "NBA"},
    {"name": "Demario Davis", "sport": "NFL"},
    {"name": "DeMar DeRozan", "sport": "NBA"},
    {"name": "Dennis Bergkamp", "sport": "Soccer"},
    {"name": "Dennis Schröder", "sport": "NBA"},
    {"name": "Deoxys", "sport": "Pokemon"},
    {"name": "Derek Jeter", "sport": "MLB"},
    {"name": "Derrick Henry", "sport": "NFL"},
    {"name": "Derrick Rose", "sport": "NBA"},
    {"name": "Derrick White", "sport": "NBA"},
    {"name": "Derwin James", "sport": "NFL"},
    {"name": "Devin Vassell", "sport": "NBA"},
    {"name": "DeVonta Smith", "sport": "NFL"},
    {"name": "Dexter Lawrence", "sport": "NFL"},
    {"name": "Dialga", "sport": "Pokemon"},
    {"name": "Dick Butkus", "sport": "NFL"},
    {"name": "Didier Drogba", "sport": "Soccer"},
    {"name": "Diego Maradona", "sport": "Soccer"},
    {"name": "Dillon Brooks", "sport": "NBA"},
    {"name": "Diogo Jota", "sport": "Soccer"},
    {"name": "Dion Dawkins", "sport": "NFL"},
    {"name": "Dirk Nowitzki", "sport": "NBA"},
    {"name": "DK Metcalf", "sport": "NFL"},
    {"name": "DJ LeMahieu", "sport": "MLB"},
    {"name": "Dominik Mysterio", "sport": "WWE"},
    {"name": "Dominik Szoboszlai", "sport": "Soccer"},
    {"name": "Dorian Finney-Smith", "sport": "NBA"},
    {"name": "Doug McDermott", "sport": "NBA"},
    {"name": "Dragonite", "sport": "Pokemon"},
    {"name": "Drake London", "sport": "NFL"},
    {"name": "Draymond Green", "sport": "NBA"},
    {"name": "Dre Greenlaw", "sport": "NFL"},
    {"name": "Drew McIntyre", "sport": "WWE"},
    {"name": "Dries Mertens", "sport": "Soccer"},
    {"name": "Druw Jones", "sport": "MLB"},
    {"name": "Druddigon", "sport": "Pokemon"},
    {"name": "Duncan Robinson", "sport": "NBA"},
    {"name": "Durant", "sport": "Pokemon"},
    {"name": "Dusknoir", "sport": "Pokemon"},
    {"name": "Dwyane Wade", "sport": "NBA"},
    {"name": "Dylan Cease", "sport": "MLB"},
    {"name": "D'Angelo Russell", "sport": "NBA"},
    {"name": "De'Anthony Melton", "sport": "NBA"},
    {"name": "Eddie Guerrero", "sport": "WWE"},
    {"name": "Eden Hazard", "sport": "Soccer"},
    {"name": "Ederson", "sport": "Soccer"},
    {"name": "Edge", "sport": "WWE"},
    {"name": "Edinson Cavani", "sport": "Soccer"},
    {"name": "Eelektross", "sport": "Pokemon"},
    {"name": "Elijah Green", "sport": "MLB"},
    {"name": "Elfrid Payton", "sport": "NBA"},
    {"name": "Elly De La Cruz", "sport": "MLB"},
    {"name": "Emboar", "sport": "Pokemon"},
    {"name": "Emolga", "sport": "Pokemon"},
    {"name": "Emmitt Smith", "sport": "NFL"},
    {"name": "Emmanuel Clase", "sport": "MLB"},
    {"name": "Enes Kanter", "sport": "NBA"},
    {"name": "Entei", "sport": "Pokemon"},
    {"name": "Enzo Fernández", "sport": "Soccer"},
    {"name": "Eric Cantona", "sport": "Soccer"},
    {"name": "Eric Gordon", "sport": "NBA"},
    {"name": "Escavalier", "sport": "Pokemon"},
    {"name": "Espeon", "sport": "Pokemon"},
    {"name": "Eusébio", "sport": "Soccer"},
    {"name": "Evan Ferguson", "sport": "Soccer"},
    {"name": "Evan Fournier", "sport": "NBA"},
    {"name": "Excadrill", "sport": "Pokemon"},
    {"name": "Ezekiel Elliott", "sport": "NFL"},
    {"name": "Ezequiel Tovar", "sport": "MLB"},
    {"name": "Fabinho", "sport": "Soccer"},
    {"name": "Fabio Cannavaro", "sport": "Soccer"},
    {"name": "Facundo Campazzo", "sport": "NBA"},
    {"name": "Ferenc Puskás", "sport": "Soccer"},
    {"name": "Feraligatr", "sport": "Pokemon"},
    {"name": "Fernandinho", "sport": "Soccer"},
    {"name": "Ferrothorn", "sport": "Pokemon"},
    {"name": "Félix Bautista", "sport": "MLB"},
    {"name": "Finn Bálor", "sport": "WWE"},
    {"name": "Flareon", "sport": "Pokemon"},
    {"name": "Flygon", "sport": "Pokemon"},
    {"name": "Framber Valdez", "sport": "MLB"},
    {"name": "Francesco Totti", "sport": "Soccer"},
    {"name": "Francisco Lindor", "sport": "MLB"},
    {"name": "Franco Baresi", "sport": "Soccer"},
    {"name": "Franck Ribéry", "sport": "Soccer"},
    {"name": "Frank Lampard", "sport": "Soccer"},
    {"name": "Frankie Luvu", "sport": "NFL"},
    {"name": "Franz Beckenbauer", "sport": "Soccer"},
    {"name": "Fred VanVleet", "sport": "NBA"},
    {"name": "Fred Warner", "sport": "NFL"},
    {"name": "Freddie Freeman", "sport": "MLB"},
    {"name": "Frenkie de Jong", "sport": "Soccer"},
    {"name": "Froslass", "sport": "Pokemon"},
    {"name": "Gabe Vincent", "sport": "NBA"},
    {"name": "Gabriel Jesus", "sport": "Soccer"},
    {"name": "Gabriel Moreno", "sport": "MLB"},
    {"name": "Gallade", "sport": "Pokemon"},
    {"name": "Galvantula", "sport": "Pokemon"},
    {"name": "Garchomp", "sport": "Pokemon"},
    {"name": "Gardevoir", "sport": "Pokemon"},
    {"name": "Garbodor", "sport": "Pokemon"},
    {"name": "Gareth Bale", "sport": "Soccer"},
    {"name": "Gary Sanchez", "sport": "MLB"},
    {"name": "Gary Trent Jr.", "sport": "NBA"},
    {"name": "Genesect", "sport": "Pokemon"},
    {"name": "Gengar", "sport": "Pokemon"},
    {"name": "George Best", "sport": "Soccer"},
    {"name": "George Hill", "sport": "NBA"},
    {"name": "George Kittle", "sport": "NFL"},
    {"name": "George Springer", "sport": "MLB"},
    {"name": "Gerard Piqué", "sport": "Soccer"},
    {"name": "Gerd Müller", "sport": "Soccer"},
    {"name": "Gerrit Cole", "sport": "MLB"},
    {"name": "Giancarlo Stanton", "sport": "MLB"},
    {"name": "Gianluigi Buffon", "sport": "Soccer"},
    {"name": "Gianluigi Donnarumma", "sport": "Soccer"},
    {"name": "Gigalith", "sport": "Pokemon"},
    {"name": "Giorgio Chiellini", "sport": "Soccer"},
    {"name": "Giratina", "sport": "Pokemon"},
    {"name": "Glaceon", "sport": "Pokemon"},
    {"name": "Golurk", "sport": "Pokemon"},
    {"name": "Gonzalo Higuaín", "sport": "Soccer"},
    {"name": "Goran Dragić", "sport": "NBA"},
    {"name": "Gordie Howe", "sport": "NHL"},
    {"name": "Gordon Hayward", "sport": "NBA"},
    {"name": "Gothitelle", "sport": "Pokemon"},
    {"name": "Grayson Allen", "sport": "NBA"},
    {"name": "Groudon", "sport": "Pokemon"},
    {"name": "Gunther", "sport": "WWE"},
    {"name": "Gyarados", "sport": "Pokemon"},
    {"name": "Haason Reddick", "sport": "NFL"},
    {"name": "Hakeem Olajuwon", "sport": "NBA"},
    {"name": "Ha-Seong Kim", "sport": "MLB"},
    {"name": "Hank Aaron", "sport": "MLB"},
    {"name": "Harrison Barnes", "sport": "NBA"},
    {"name": "Harrison Smith", "sport": "NFL"},
    {"name": "Harry Kane", "sport": "Soccer"},
    {"name": "Harry Maguire", "sport": "Soccer"},
    {"name": "Hassan Whiteside", "sport": "NBA"},
    {"name": "Haxorus", "sport": "Pokemon"},
    {"name": "Heatmor", "sport": "Pokemon"},
    {"name": "Heatran", "sport": "Pokemon"},
    {"name": "Herbert Jones", "sport": "NBA"},
    {"name": "Honchkrow", "sport": "Pokemon"},
    {"name": "Ho-Oh", "sport": "Pokemon"},
    {"name": "Houndoom", "sport": "Pokemon"},
    {"name": "Hulk Hogan", "sport": "WWE"},
    {"name": "Hunter Renfroe", "sport": "MLB"},
    {"name": "Hydreigon", "sport": "Pokemon"},
    {"name": "Iker Casillas", "sport": "Soccer"},
    {"name": "Isaac Okoro", "sport": "NBA"},
    {"name": "Isco", "sport": "Soccer"},
    {"name": "Isaiah Stewart", "sport": "NBA"},
    {"name": "Ivan Rakitić", "sport": "Soccer"},
    {"name": "Ivica Zubac", "sport": "NBA"},
    {"name": "Jabari Smith Jr.", "sport": "NBA"},
    {"name": "Jace Jung", "sport": "MLB"},
    {"name": "Jackie Robinson", "sport": "MLB"},
    {"name": "Jackson Chourio", "sport": "MLB"},
    {"name": "Jackson Holliday", "sport": "MLB"},
    {"name": "Jacob deGrom", "sport": "MLB"},
    {"name": "Jaden McDaniels", "sport": "NBA"},
    {"name": "Jae Crowder", "sport": "NBA"},
    {"name": "Jae'Sean Tate", "sport": "NBA"},
    {"name": "James Cook", "sport": "NFL"},
    {"name": "James Harden", "sport": "NBA"},
    {"name": "James Karinchak", "sport": "MLB"},
    {"name": "James Rodríguez", "sport": "Soccer"},
    {"name": "James Wiseman", "sport": "NBA"},
    {"name": "James Wood", "sport": "MLB"},
    {"name": "Jamie Vardy", "sport": "Soccer"},
    {"name": "Jan Oblak", "sport": "Soccer"},
    {"name": "Jared Goff", "sport": "NFL"},
    {"name": "Jared Verse", "sport": "NFL"},
    {"name": "Jared Walsh", "sport": "MLB"},
    {"name": "Jaromír Jágr", "sport": "NHL"},
    {"name": "Jarred Kelenic", "sport": "MLB"},
    {"name": "Jarren Duran", "sport": "MLB"},
    {"name": "Jarrett Allen", "sport": "NBA"},
    {"name": "Jaylen Waddle", "sport": "NFL"},
    {"name": "Jeff Green", "sport": "NBA"},
    {"name": "Jeff McNeil", "sport": "MLB"},
    {"name": "Jeffery Simmons", "sport": "NFL"},
    {"name": "Jellicent", "sport": "Pokemon"},
    {"name": "Jerami Grant", "sport": "NBA"},
    {"name": "Jeremy Peña", "sport": "MLB"},
    {"name": "Jérôme Boateng", "sport": "Soccer"},
    {"name": "Jerry Jeudy", "sport": "NFL"},
    {"name": "Jerry Rice", "sport": "NFL"},
    {"name": "Jessie Bates III", "sport": "NFL"},
    {"name": "Jey Uso", "sport": "WWE"},
    {"name": "Jhoan Duran", "sport": "MLB"},
    {"name": "Jim Brown", "sport": "NFL"},
    {"name": "Jimmy Butler", "sport": "NBA"},
    {"name": "Jimmy Uso", "sport": "WWE"},
    {"name": "Jirachi", "sport": "Pokemon"},
    {"name": "J.D. Martinez", "sport": "MLB"},
    {"name": "J.J. Redick", "sport": "NBA"},
    {"name": "J.T. Realmuto", "sport": "MLB"},
    {"name": "João Cancelo", "sport": "Soccer"},
    {"name": "Joc Pederson", "sport": "MLB"},
    {"name": "Joe Harris", "sport": "NBA"},
    {"name": "Joe Ingles", "sport": "NBA"},
    {"name": "Joe Mixon", "sport": "NFL"},
    {"name": "Joe Montana", "sport": "NFL"},
    {"name": "Joe Musgrove", "sport": "MLB"},
    {"name": "Joey Bosa", "sport": "NFL"},
    {"name": "Joey Gallo", "sport": "MLB"},
    {"name": "Johan Cruyff", "sport": "Soccer"},
    {"name": "John Cena", "sport": "WWE"},
    {"name": "John Elway", "sport": "NFL"},
    {"name": "John Terry", "sport": "Soccer"},
    {"name": "John Wall", "sport": "NBA"},
    {"name": "Jolteon", "sport": "Pokemon"},
    {"name": "Jonah Heim", "sport": "MLB"},
    {"name": "Jonathan Allen", "sport": "NFL"},
    {"name": "Jonathan Huberdeau", "sport": "NHL"},
    {"name": "Jonathan Kuminga", "sport": "NBA"},
    {"name": "Jordan Howard", "sport": "NFL"},
    {"name": "Jordan Lawlar", "sport": "MLB"},
    {"name": "Jordan Love", "sport": "NFL"},
    {"name": "Jordan Mailata", "sport": "NFL"},
    {"name": "Jordan Poole", "sport": "NBA"},
    {"name": "Jordan Poyer", "sport": "NFL"},
    {"name": "Jordan Romano", "sport": "MLB"},
    {"name": "Jordan Walker", "sport": "MLB"},
    {"name": "Jorge Polanco", "sport": "MLB"},
    {"name": "Jorge Soler", "sport": "MLB"},
    {"name": "Jorginho", "sport": "Soccer"},
    {"name": "José Ramírez", "sport": "MLB"},
    {"name": "Jose Abreu", "sport": "MLB"},
    {"name": "Jose Altuve", "sport": "MLB"},
    {"name": "Josh Bell", "sport": "MLB"},
    {"name": "Josh Hader", "sport": "MLB"},
    {"name": "Josh Hart", "sport": "NBA"},
    {"name": "Josh Hines-Allen", "sport": "NFL"},
    {"name": "Josh Lowe", "sport": "MLB"},
    {"name": "Josh Richardson", "sport": "NBA"},
    {"name": "Josh Sweat", "sport": "NFL"},
    {"name": "Joshua Kimmich", "sport": "Soccer"},
    {"name": "Josko Gvardiol", "sport": "Soccer"},
    {"name": "Jrue Holiday", "sport": "NBA"},
    {"name": "JuJu Smith-Schuster", "sport": "NFL"},
    {"name": "Julian Love", "sport": "NFL"},
    {"name": "Julio Jones", "sport": "NFL"},
    {"name": "Julio Urías", "sport": "MLB"},
    {"name": "Julius Randle", "sport": "NBA"},
    {"name": "Jung Ho Kang", "sport": "MLB"},
    {"name": "Jusuf Nurkić", "sport": "NBA"},
    {"name": "Justin Kluivert", "sport": "Soccer"},
    {"name": "Justin Madubuike", "sport": "NFL"},
    {"name": "Justin Simmons", "sport": "NFL"},
    {"name": "Justin Turner", "sport": "MLB"},
    {"name": "Justin Verlander", "sport": "MLB"},
    {"name": "Kalidou Koulibaly", "sport": "Soccer"},
    {"name": "Kane", "sport": "WWE"},
    {"name": "Karim Adeyemi", "sport": "Soccer"},
    {"name": "Karim Benzema", "sport": "Soccer"},
    {"name": "Kasper Dolberg", "sport": "Soccer"},
    {"name": "Kawhi Leonard", "sport": "NBA"},
    {"name": "Ke’Bryan Hayes", "sport": "MLB"},
    {"name": "Keldeo", "sport": "Pokemon"},
    {"name": "Keldon Johnson", "sport": "NBA"},
    {"name": "Kelly Oubre Jr.", "sport": "NBA"},
    {"name": "Kemba Walker", "sport": "NBA"},
    {"name": "Kenyon Martin Jr.", "sport": "NBA"},
    {"name": "Kerby Joseph", "sport": "NFL"},
    {"name": "Ketel Marte", "sport": "MLB"},
    {"name": "Kevin De Bruyne", "sport": "Soccer"},
    {"name": "Kevin Durant", "sport": "NBA"},
    {"name": "Kevin Gausman", "sport": "MLB"},
    {"name": "Kevin Love", "sport": "NBA"},
    {"name": "Kevin Owens", "sport": "WWE"},
    {"name": "Khalil Mack", "sport": "NFL"},
    {"name": "Khris Middleton", "sport": "NBA"},
    {"name": "Kingsley Coman", "sport": "Soccer"},
    {"name": "Kirk Cousins", "sport": "NFL"},
    {"name": "Klay Thompson", "sport": "NBA"},
    {"name": "Klinklang", "sport": "Pokemon"},
    {"name": "Kobe Bryant", "sport": "NBA"},
    {"name": "Kofi Kingston", "sport": "WWE"},
    {"name": "Kris Bryant", "sport": "MLB"},
    {"name": "Kristaps Porziņģis", "sport": "NBA"},
    {"name": "Krookodile", "sport": "Pokemon"},
    {"name": "Kyle Hamilton", "sport": "NFL"},
    {"name": "Kyle Lowry", "sport": "NBA"},
    {"name": "Kyle Schwarber", "sport": "MLB"},
    {"name": "Kyle Tucker", "sport": "MLB"},
    {"name": "Kyogre", "sport": "Pokemon"},
    {"name": "Kyren Williams", "sport": "NFL"},
    {"name": "Kyrie Irving", "sport": "NBA"},
    {"name": "Kyurem", "sport": "Pokemon"},
    {"name": "Ladd McConkey", "sport": "NFL"},
    {"name": "Landorus", "sport": "Pokemon"},
    {"name": "Landry Shamet", "sport": "NBA"},
    {"name": "Lane Johnson", "sport": "NFL"},
    {"name": "Laremy Tunsil", "sport": "NFL"},
    {"name": "Larry Bird", "sport": "NBA"},
    {"name": "Latias", "sport": "Pokemon"},
    {"name": "Latios", "sport": "Pokemon"},
    {"name": "Lautaro Martínez", "sport": "Soccer"},
    {"name": "Lavonte David", "sport": "NFL"},
    {"name": "Lawrence Taylor", "sport": "NFL"},
    {"name": "Leafeon", "sport": "Pokemon"},
    {"name": "Leavanny", "sport": "Pokemon"},
    {"name": "Leon Draisaitl", "sport": "NHL"},
    {"name": "Leon Goretzka", "sport": "Soccer"},
    {"name": "Leonard Williams", "sport": "NFL"},
    {"name": "Leonardo Bonucci", "sport": "Soccer"},
    {"name": "Leroy Sané", "sport": "Soccer"},
    {"name": "Liam Hendriks", "sport": "MLB"},
    {"name": "Liepard", "sport": "Pokemon"},
    {"name": "Lilligant", "sport": "Pokemon"},
    {"name": "Lionel Messi", "sport": "Soccer"},
    {"name": "Lita", "sport": "WWE"},
    {"name": "Liv Morgan", "sport": "WWE"},
    {"name": "Logan Webb", "sport": "MLB"},
    {"name": "Logan Paul", "sport": "WWE"},
    {"name": "Lorenzo Insigne", "sport": "Soccer"},
    {"name": "Lou Gehrig", "sport": "MLB"},
    {"name": "Lou Williams", "sport": "NBA"},
    {"name": "Lourdes Gurriel Jr.", "sport": "MLB"},
    {"name": "Lucario", "sport": "Pokemon"},
    {"name": "Luguentz Dort", "sport": "NBA"},
    {"name": "Lugia", "sport": "Pokemon"},
    {"name": "Luis Castillo", "sport": "MLB"},
    {"name": "Luis Severino", "sport": "MLB"},
    {"name": "Luis Suárez", "sport": "Soccer"},
    {"name": "Luís Figo", "sport": "Soccer"},
    {"name": "Luke Kennard", "sport": "NBA"},
    {"name": "Machamp", "sport": "Pokemon"},
    {"name": "Macho Man Randy Savage", "sport": "WWE"},
    {"name": "Magic Johnson", "sport": "NBA"},
    {"name": "Magmortar", "sport": "Pokemon"},
    {"name": "Malcolm Brogdon", "sport": "NBA"},
    {"name": "Malik Beasley", "sport": "NBA"},
    {"name": "Malik Nabers", "sport": "NFL"},
    {"name": "Mamoswine", "sport": "Pokemon"},
    {"name": "Manectric", "sport": "Pokemon"},
    {"name": "Mandibuzz", "sport": "Pokemon"},
    {"name": "Manny Machado", "sport": "MLB"},
    {"name": "Manu Ginóbili", "sport": "NBA"},
    {"name": "Manuel Neuer", "sport": "Soccer"},
    {"name": "Maractus", "sport": "Pokemon"},
    {"name": "Marc Gasol", "sport": "NBA"},
    {"name": "Marc-André ter Stegen", "sport": "Soccer"},
    {"name": "Marcelo", "sport": "Soccer"},
    {"name": "Marco Reus", "sport": "Soccer"},
    {"name": "Marco van Basten", "sport": "Soccer"},
    {"name": "Marco Verratti", "sport": "Soccer"},
    {"name": "Marcus Mariota", "sport": "NFL"},
    {"name": "Marcus Peters", "sport": "NFL"},
    {"name": "Marcus Rashford", "sport": "Soccer"},
    {"name": "Marcus Semien", "sport": "MLB"},
    {"name": "Marcus Smart", "sport": "NBA"},
    {"name": "Mario Lemieux", "sport": "NHL"},
    {"name": "Mark Canha", "sport": "MLB"},
    {"name": "Mark Messier", "sport": "NHL"},
    {"name": "Marquinhos", "sport": "Soccer"},
    {"name": "Marshon Lattimore", "sport": "NFL"},
    {"name": "Martin Brodeur", "sport": "NHL"},
    {"name": "Marvin Bagley III", "sport": "NBA"},
    {"name": "Masataka Yoshida", "sport": "MLB"},
    {"name": "Matisse Thybulle", "sport": "NBA"},
    {"name": "Mats Hummels", "sport": "Soccer"},
    {"name": "Matt Duffy", "sport": "MLB"},
    {"name": "Matt Olson", "sport": "MLB"},
    {"name": "Mauro Icardi", "sport": "Soccer"},
    {"name": "Max Kepler", "sport": "MLB"},
    {"name": "Max Scherzer", "sport": "MLB"},
    {"name": "Max Strus", "sport": "NBA"},
    {"name": "Maxx Crosby", "sport": "NFL"},
    {"name": "Meganium", "sport": "Pokemon"},
    {"name": "Meloetta", "sport": "Pokemon"},
    {"name": "Mesprit", "sport": "Pokemon"},
    {"name": "Mesut Özil", "sport": "Soccer"},
    {"name": "Metagross", "sport": "Pokemon"},
    {"name": "Mew", "sport": "Pokemon"},
    {"name": "Mewtwo", "sport": "Pokemon"},
    {"name": "Michael Conforto", "sport": "MLB"},
    {"name": "Michael Fulmer", "sport": "MLB"},
    {"name": "Michael Jordan", "sport": "NBA"},
    {"name": "Michael Platini", "sport": "Soccer"},
    {"name": "Michel Platini", "sport": "Soccer"},
    {"name": "Mick Foley", "sport": "WWE"},
    {"name": "Mickey Mantle", "sport": "MLB"},
    {"name": "Mienshao", "sport": "Pokemon"},
    {"name": "Miguel Andújar", "sport": "MLB"},
    {"name": "Miguel Vargas", "sport": "MLB"},
    {"name": "Mikal Bridges", "sport": "NBA"},
    {"name": "Mike Conley", "sport": "NBA"},
    {"name": "Mike Evans", "sport": "NFL"},
    {"name": "Mike Trout", "sport": "MLB"},
    {"name": "Mike Yastrzemski", "sport": "MLB"},
    {"name": "Mikko Rantanen", "sport": "NHL"},
    {"name": "Milotic", "sport": "Pokemon"},
    {"name": "Minkah Fitzpatrick", "sport": "NFL"},
    {"name": "Mitchell Robinson", "sport": "NBA"},
    {"name": "MJ Melendez", "sport": "MLB"},
    {"name": "Mo Bamba", "sport": "NBA"},
    {"name": "Mohamed Salah", "sport": "Soccer"},
    {"name": "Moltres", "sport": "Pokemon"},
    {"name": "Montez Ford", "sport": "WWE"},
    {"name": "Montez Sweat", "sport": "NFL"},
    {"name": "Montrezl Harrell", "sport": "NBA"},
    {"name": "Mookie Betts", "sport": "MLB"},
    {"name": "Moses Moody", "sport": "NBA"},
    {"name": "Moussa Diaby", "sport": "Soccer"},
    {"name": "Musharna", "sport": "Pokemon"},
    {"name": "Myles Garrett", "sport": "NFL"},
    {"name": "Myles Turner", "sport": "NBA"},
    {"name": "N'Golo Kanté", "sport": "Soccer"},
    {"name": "Nathan MacKinnon", "sport": "NHL"},
    {"name": "Nathaniel Lowe", "sport": "MLB"},
    {"name": "Natalya", "sport": "WWE"},
    {"name": "Naz Reid", "sport": "NBA"},
    {"name": "Nerlens Noel", "sport": "NBA"},
    {"name": "Neymar", "sport": "Soccer"},
    {"name": "Nikita Kucherov", "sport": "NHL"},
    {"name": "Nikola Mirotic", "sport": "NBA"},
    {"name": "Nikola Vucevic", "sport": "NBA"},
    {"name": "Nicolò Zaniolo", "sport": "Soccer"},
    {"name": "Noah Syndergaard", "sport": "MLB"},
    {"name": "Nolan Arenado", "sport": "MLB"},
    {"name": "Nolan Gorman", "sport": "MLB"},
    {"name": "Nolan Ryan", "sport": "MLB"},
    {"name": "Norman Powell", "sport": "NBA"},
    {"name": "Nuno Mendes", "sport": "Soccer"},
    {"name": "Obi Toppin", "sport": "NBA"},
    {"name": "OG Anunoby", "sport": "NBA"},
    {"name": "Oneil Cruz", "sport": "MLB"},
    {"name": "Onyeka Okongwu", "sport": "NBA"},
    {"name": "Oswald Peraza", "sport": "MLB"},
    {"name": "Oswaldo Cabrera", "sport": "MLB"},
    {"name": "Ousmane Dembélé", "sport": "Soccer"},
    {"name": "Ozzie Albies", "sport": "MLB"},
    {"name": "Pablo López", "sport": "MLB"},
    {"name": "Palkia", "sport": "Pokemon"},
    {"name": "Paolo Maldini", "sport": "Soccer"},
    {"name": "Patrick Beverley", "sport": "NBA"},
    {"name": "Patrick Cutrone", "sport": "Soccer"},
    {"name": "Patrick Kane", "sport": "NHL"},
    {"name": "Patrick Queen", "sport": "NFL"},
    {"name": "Patrick Roy", "sport": "NHL"},
    {"name": "Patrick Surtain II", "sport": "NFL"},
    {"name": "Patrick Vieira", "sport": "Soccer"},
    {"name": "Patrick Williams", "sport": "NBA"},
    {"name": "Patty Mills", "sport": "NBA"},
    {"name": "Paul George", "sport": "NBA"},
    {"name": "Paul Goldschmidt", "sport": "MLB"},
    {"name": "Paul Millsap", "sport": "NBA"},
    {"name": "Paul Pogba", "sport": "Soccer"},
    {"name": "Paul Scholes", "sport": "Soccer"},
    {"name": "Pau Gasol", "sport": "NBA"},
    {"name": "Paulo Dybala", "sport": "Soccer"},
    {"name": "Pavel Nedvěd", "sport": "Soccer"},
    {"name": "Pelé", "sport": "Soccer"},
    {"name": "Penei Sewell", "sport": "NFL"},
    {"name": "Pepe", "sport": "Soccer"},
    {"name": "Pete Crow-Armstrong", "sport": "MLB"},
    {"name": "Peyton Manning", "sport": "NFL"},
    {"name": "Philipp Lahm", "sport": "Soccer"},
    {"name": "Phillip Lindsay", "sport": "NFL"},
    {"name": "Pierre-Emerick Aubameyang", "sport": "Soccer"},
    {"name": "Pikachu", "sport": "Pokemon"},
    {"name": "PJ Washington", "sport": "NBA"},
    {"name": "P.J. Tucker", "sport": "NBA"},
    {"name": "Porygon-Z", "sport": "Pokemon"},
    {"name": "Precious Achiuwa", "sport": "NBA"},
    {"name": "Probopass", "sport": "Pokemon"},
    {"name": "Quincy Williams", "sport": "NFL"},
    {"name": "Quinnen Williams", "sport": "NFL"},
    {"name": "Rafael Devers", "sport": "MLB"},
    {"name": "Raheem Mostert", "sport": "NFL"},
    {"name": "Raheem Sterling", "sport": "Soccer"},
    {"name": "Raikou", "sport": "Pokemon"},
    {"name": "Rajon Rondo", "sport": "NBA"},
    {"name": "Randy Moss", "sport": "NFL"},
    {"name": "Randy Orton", "sport": "WWE"},
    {"name": "Raphaël Varane", "sport": "Soccer"},
    {"name": "Rashan Gary", "sport": "NFL"},
    {"name": "Raul Neto", "sport": "NBA"},
    {"name": "Raúl González", "sport": "Soccer"},
    {"name": "Ray Bourque", "sport": "NHL"},
    {"name": "Ray Lewis", "sport": "NFL"},
    {"name": "Rayquaza", "sport": "Pokemon"},
    {"name": "Reggie Jackson", "sport": "NBA"},
    {"name": "Reggie White", "sport": "NFL"},
    {"name": "Regigigas", "sport": "Pokemon"},
    {"name": "Reshiram", "sport": "Pokemon"},
    {"name": "Reuniclus", "sport": "Pokemon"},
    {"name": "Rhea Ripley", "sport": "WWE"},
    {"name": "Rhys Hoskins", "sport": "MLB"},
    {"name": "Rhyperior", "sport": "Pokemon"},
    {"name": "Ric Flair", "sport": "WWE"},
    {"name": "Richaun Holmes", "sport": "NBA"},
    {"name": "Ricky Rubio", "sport": "NBA"},
    {"name": "Riley Greene", "sport": "MLB"},
    {"name": "Rivaldo", "sport": "Soccer"},
    {"name": "Riyad Mahrez", "sport": "Soccer"},
    {"name": "Rob Gronkowski", "sport": "NFL"},
    {"name": "Robbie Ray", "sport": "MLB"},
    {"name": "Robert Covington", "sport": "NBA"},
    {"name": "Robert Lewandowski", "sport": "Soccer"},
    {"name": "Robert Williams III", "sport": "NBA"},
    {"name": "Roberto Baggio", "sport": "Soccer"},
    {"name": "Roberto Firmino", "sport": "Soccer"},
    {"name": "Roddy Piper", "sport": "WWE"},
    {"name": "Roman Josi", "sport": "NHL"},
    {"name": "Roman Reigns", "sport": "WWE"},
    {"name": "Ronaldinho", "sport": "Soccer"},
    {"name": "Ronaldo Nazário", "sport": "Soccer"},
    {"name": "Ronda Rousey", "sport": "WWE"},
    {"name": "Roquan Smith", "sport": "NFL"},
    {"name": "Rotom", "sport": "Pokemon"},
    {"name": "Roy Keane", "sport": "Soccer"},
    {"name": "Royce Lewis", "sport": "MLB"},
    {"name": "Royce O'Neale", "sport": "NBA"},
    {"name": "Rudy Gobert", "sport": "NBA"},
    {"name": "Russell Westbrook", "sport": "NBA"},
    {"name": "Russell Wilson", "sport": "NFL"},
    {"name": "Ryan Giggs", "sport": "Soccer"},
    {"name": "Ryan Mountcastle", "sport": "MLB"},
    {"name": "Ryan Pressly", "sport": "MLB"},
    {"name": "Ryan Sessegnon", "sport": "Soccer"},
    {"name": "Rúben Dias", "sport": "Soccer"},
    {"name": "Saddiq Bey", "sport": "NBA"},
    {"name": "Sadio Mané", "sport": "Soccer"},
    {"name": "Salamence", "sport": "Pokemon"},
    {"name": "Salvador Perez", "sport": "MLB"},
    {"name": "Sami Zayn", "sport": "WWE"},
    {"name": "Samurott", "sport": "Pokemon"},
    {"name": "Samuel Eto'o", "sport": "Soccer"},
    {"name": "Sandy Alcantara", "sport": "MLB"},
    {"name": "Sasha Banks", "sport": "WWE"},
    {"name": "Sawk", "sport": "Pokemon"},
    {"name": "Sawsbuck", "sport": "Pokemon"},
    {"name": "Sceptile", "sport": "Pokemon"},
    {"name": "Scizor", "sport": "Pokemon"},
    {"name": "Scolipede", "sport": "Pokemon"},
    {"name": "Scrafty", "sport": "Pokemon"},
    {"name": "Sean Murphy", "sport": "MLB"},
    {"name": "Seismitoad", "sport": "Pokemon"},
    {"name": "Seiya Suzuki", "sport": "MLB"},
    {"name": "Serge Gnabry", "sport": "Soccer"},
    {"name": "Serge Ibaka", "sport": "NBA"},
    {"name": "Sergio Agüero", "sport": "Soccer"},
    {"name": "Sergio Busquets", "sport": "Soccer"},
    {"name": "Sergio Ramos", "sport": "Soccer"},
    {"name": "Serperior", "sport": "Pokemon"},
    {"name": "Seth Curry", "sport": "NBA"},
    {"name": "Seth Rollins", "sport": "WWE"},
    {"name": "Shane Bieber", "sport": "MLB"},
    {"name": "Shane McClanahan", "sport": "MLB"},
    {"name": "Shaquille O'Neal", "sport": "NBA"},
    {"name": "Shaun Livingston", "sport": "NBA"},
    {"name": "Shawn Michaels", "sport": "WWE"},
    {"name": "Shaymin", "sport": "Pokemon"},
    {"name": "Shayna Baszler", "sport": "WWE"},
    {"name": "Shinsuke Nakamura", "sport": "WWE"},
    {"name": "Sidney Crosby", "sport": "NHL"},
    {"name": "Sigilyph", "sport": "Pokemon"},
    {"name": "Simisage", "sport": "Pokemon"},
    {"name": "Simisear", "sport": "Pokemon"},
    {"name": "Simipour", "sport": "Pokemon"},
    {"name": "Snorlax", "sport": "Pokemon"},
    {"name": "Son Heung-min", "sport": "Soccer"},
    {"name": "Spencer Steer", "sport": "MLB"},
    {"name": "Spencer Torkelson", "sport": "MLB"},
    {"name": "Spiritomb", "sport": "Pokemon"},
    {"name": "Starling Marte", "sport": "MLB"},
    {"name": "Steelix", "sport": "Pokemon"},
    {"name": "Stefon Diggs", "sport": "NFL"},
    {"name": "Steven Adams", "sport": "NBA"},
    {"name": "Steven Gerrard", "sport": "Soccer"},
    {"name": "Steven Kwan", "sport": "MLB"},
    {"name": "Steven Stamkos", "sport": "NHL"},
    {"name": "Stone Cold Steve Austin", "sport": "WWE"},
    {"name": "Stoutland", "sport": "Pokemon"},
    {"name": "Stunfisk", "sport": "Pokemon"},
    {"name": "Suicune", "sport": "Pokemon"},
    {"name": "Swampert", "sport": "Pokemon"},
    {"name": "Swanna", "sport": "Pokemon"},
    {"name": "Swoobat", "sport": "Pokemon"},
    {"name": "Tanner Bibee", "sport": "MLB"},
    {"name": "Tangrowth", "sport": "Pokemon"},
    {"name": "Tariq Woolen", "sport": "NFL"},
    {"name": "Taylor Ward", "sport": "MLB"},
    {"name": "Ted Williams", "sport": "MLB"},
    {"name": "Tee Higgins", "sport": "NFL"},
    {"name": "Teoscar Hernández", "sport": "MLB"},
    {"name": "Termarr Johnson", "sport": "MLB"},
    {"name": "Terrakion", "sport": "Pokemon"},
    {"name": "Terrence Ross", "sport": "NBA"},
    {"name": "Terron Armstead", "sport": "NFL"},
    {"name": "Terry McLaurin", "sport": "NFL"},
    {"name": "Terry Rozier", "sport": "NBA"},
    {"name": "Thaddeus Young", "sport": "NBA"},
    {"name": "The Miz", "sport": "WWE"},
    {"name": "The Rock", "sport": "WWE"},
    {"name": "The Undertaker", "sport": "WWE"},
    {"name": "Thiago Alcântara", "sport": "Soccer"},
    {"name": "Thierry Henry", "sport": "Soccer"},
    {"name": "Thibaut Courtois", "sport": "Soccer"},
    {"name": "Thomas Müller", "sport": "Soccer"},
    {"name": "Throh", "sport": "Pokemon"},
    {"name": "Thundurus", "sport": "Pokemon"},
    {"name": "Tim Anderson", "sport": "MLB"},
    {"name": "Tim Duncan", "sport": "NBA"},
    {"name": "Timo Werner", "sport": "Soccer"},
    {"name": "T.J. McConnell", "sport": "NBA"},
    {"name": "T.J. Warren", "sport": "NBA"},
    {"name": "Tobias Harris", "sport": "NBA"},
    {"name": "Todd Gurley", "sport": "NFL"},
    {"name": "Togekiss", "sport": "Pokemon"},
    {"name": "Tom Brady", "sport": "NFL"},
    {"name": "Tommy Edman", "sport": "MLB"},
    {"name": "Toni Kroos", "sport": "Soccer"},
    {"name": "Tony Parker", "sport": "NBA"},
    {"name": "Tornadus", "sport": "Pokemon"},
    {"name": "Toxicroak", "sport": "Pokemon"},
    {"name": "Travis d'Arnaud", "sport": "MLB"},
    {"name": "Travis Kelce", "sport": "NFL"},
    {"name": "Trea Turner", "sport": "MLB"},
    {"name": "Trent McDuffie", "sport": "NFL"},
    {"name": "Trent Williams", "sport": "NFL"},
    {"name": "Trevor Ariza", "sport": "NBA"},
    {"name": "Trey Hendrickson", "sport": "NFL"},
    {"name": "Trey Mancini", "sport": "MLB"},
    {"name": "Trey McBride", "sport": "NFL"},
    {"name": "Triple H", "sport": "WWE"},
    {"name": "Trish Stratus", "sport": "WWE"},
    {"name": "Tristan Wirfs", "sport": "NFL"},
    {"name": "Triston Casas", "sport": "MLB"},
    {"name": "Tua Tagovailoa", "sport": "NFL"},
    {"name": "Ty France", "sport": "MLB"},
    {"name": "Tyler Glasnow", "sport": "MLB"},
    {"name": "Tyler Naquin", "sport": "MLB"},
    {"name": "Typhlosion", "sport": "Pokemon"},
    {"name": "Tyranitar", "sport": "Pokemon"},
    {"name": "Tyreek Hill", "sport": "NFL"},
    {"name": "Tyus Jones", "sport": "NBA"},
    {"name": "Ultimate Warrior", "sport": "WWE"},
    {"name": "Umbreon", "sport": "Pokemon"},
    {"name": "Unfezant", "sport": "Pokemon"},
    {"name": "Uxie", "sport": "Pokemon"},
    {"name": "Vanilluxe", "sport": "Pokemon"},
    {"name": "Vaporeon", "sport": "Pokemon"},
    {"name": "Vaughn Grissom", "sport": "MLB"},
    {"name": "Venusaur", "sport": "Pokemon"},
    {"name": "Victor Hedman", "sport": "NHL"},
    {"name": "Victor Oladipo", "sport": "NBA"},
    {"name": "Victini", "sport": "Pokemon"},
    {"name": "Vince Carter", "sport": "NBA"},
    {"name": "Vinnie Pasquantino", "sport": "MLB"},
    {"name": "Virgil van Dijk", "sport": "Soccer"},
    {"name": "Virizion", "sport": "Pokemon"},
    {"name": "Vita Vea", "sport": "NFL"},
    {"name": "Vinícius Júnior", "sport": "Soccer"},
    {"name": "Vladimir Guerrero Jr.", "sport": "MLB"},
    {"name": "Volcarona", "sport": "Pokemon"},
    {"name": "Walker Buehler", "sport": "MLB"},
    {"name": "Walrein", "sport": "Pokemon"},
    {"name": "Walter Payton", "sport": "NFL"},
    {"name": "Watchog", "sport": "Pokemon"},
    {"name": "Wayne Gretzky", "sport": "NHL"},
    {"name": "Weavile", "sport": "Pokemon"},
    {"name": "Wendell Carter Jr.", "sport": "NBA"},
    {"name": "Whimsicott", "sport": "Pokemon"},
    {"name": "Whit Merrifield", "sport": "MLB"},
    {"name": "Will Smith", "sport": "MLB"},
    {"name": "Willie Mays", "sport": "MLB"},
    {"name": "Willy Hernangomez", "sport": "NBA"},
    {"name": "Willson Contreras", "sport": "MLB"},
    {"name": "Xabi Alonso", "sport": "Soccer"},
    {"name": "Xander Bogaerts", "sport": "MLB"},
    {"name": "Xavi Hernández", "sport": "Soccer"},
    {"name": "Xavi Simons", "sport": "Soccer"},
    {"name": "Xavier Woods", "sport": "WWE"},
    {"name": "Yanmega", "sport": "Pokemon"},
    {"name": "Yaya Touré", "sport": "Soccer"},
    {"name": "Yoshinobu Yamamoto", "sport": "MLB"},
    {"name": "Youri Tielemans", "sport": "Soccer"},
    {"name": "Yu Darvish", "sport": "MLB"},
    {"name": "Yuli Gurriel", "sport": "MLB"},
    {"name": "Zac Veen", "sport": "MLB"},
    {"name": "Zach Allen", "sport": "NFL"},
    {"name": "Zach LaVine", "sport": "NBA"},
    {"name": "Zack Martin", "sport": "NFL"},
    {"name": "Zack Wheeler", "sport": "MLB"},
    {"name": "Zaire Franklin", "sport": "NFL"},
    {"name": "Zapdos", "sport": "Pokemon"},
    {"name": "Zebstrika", "sport": "Pokemon"},
    {"name": "Zekrom", "sport": "Pokemon"},
    {"name": "Zinedine Zidane", "sport": "Soccer"},
    {"name": "Zlatan Ibrahimović", "sport": "Soccer"},
    {"name": "Zoroark", "sport": "Pokemon"},
    // Adding new players from the user
    { "name": "LeBron James", "sport": "NBA" },
    { "name": "Cooper Flagg", "sport": "NBA" },
    { "name": "Stephen Curry", "sport": "NBA" },
    { "name": "Amen Thompson", "sport": "NBA" },
    { "name": "Matas Buzelis", "sport": "NBA" },
    { "name": "Tyrese Maxey", "sport": "NBA" },
    { "name": "Jalen Brunson", "sport": "NBA" },
    { "name": "Nikola Jokić", "sport": "NBA" },
    { "name": "Giannis Antetokounmpo", "sport": "NBA" },
    { "name": "Reed Sheppard", "sport": "NBA" },
    { "name": "Bronny James Jr.", "sport": "NBA" },
    { "name": "Stephon Castle", "sport": "NBA" },
    { "name": "Alperen Şengün", "sport": "NBA" },
    { "name": "Jalen Williams", "sport": "NBA" },
    { "name": "Jaylen Brown", "sport": "NBA" },
    { "name": "Darius Garland", "sport": "NBA" },
    { "name": "Joel Embiid", "sport": "NBA" },
    { "name": "Pascal Siakam", "sport": "NBA" },
    { "name": "Devin Booker", "sport": "NBA" },
    { "name": "Franz Wagner", "sport": "NBA" },
    { "name": "Domantas Sabonis", "sport": "NBA" },
    { "name": "Karl-Anthony Towns", "sport": "NBA" },
    { "name": "Michael Porter Jr.", "sport": "NBA" },
    { "name": "Cam Whitmore", "sport": "NBA" },
    { "name": "Keyonte George", "sport": "NBA" },
    { "name": "Bilal Coulibaly", "sport": "NBA" },
    { "name": "Tari Eason", "sport": "NBA" },
    { "name": "Dylan Harper", "sport": "NBA" },
    { "name": "Ace Bailey", "sport": "NBA" },
    { "name": "Derik Queen", "sport": "NBA" }
];

const allPlayers = [...prizmRookies, ...otherPlayers];
const uniquePlayers = Array.from(new Map(allPlayers.map(player => [player.name.toLowerCase(), player])).values());
export const defaultPlayers: Player[] = uniquePlayers.sort((a, b) => a.name.localeCompare(b.name));
